kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-mini-app
  labels:
    app: my-mini-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-mini-app
  template:
    metadata:
      name: my-mini-app
      labels:
        app: my-mini-app
    spec:
      containers:
        - name: my-mini-app
          image: docker.io/aleksandrovsp/aleksandrov-my-miniapp:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-miniapp-service
spec:
  type: NodePort
  selector:
    app: my-mini-app
  ports:
    - name: my-mini-app-nginx
      protocol: TCP
      port: 80
      nodePort: 30055